12 non profit details 2
chingu-voyage5/Bears-Team-3 pull request #22
Opened 2018-06-20 11:35 UTC by ElleeB

Add non-profit/organization detail page route and basic view

2018-06-20 11:39 UTC, veredrec approved these changes
Since I didn't figure out how to run it locally (yet!) I'm not able to run and see it, but from the code itself - I think it looks good!

2018-06-20 20:38 UTC, AryanJ-NYC requested changes
@ElleeB I think the outcome of this ticket be rendered JSON instead so that it can be fetched from the front-end. That should be a quick fix though (just one line). It'll be similar to [this](https://github.com/chingu-voyage5/Bears-Team-3/commit/04892cddd6f7692b734d54f398ad7879b8722ab2).

2018-06-21 02:36 UTC, AryanJ-NYC approved these changes

2018-06-21 02:36 UTC, AryanJ-NYC commented
![screen shot 2018-06-20 at 10 35 50 pm](https://user-images.githubusercontent.com/8263430/41694850-51998eca-74da-11e8-9967-34db2a31e3b3.png)
`/organizations/:id` confirmed renders JSON. Nice work!

2018-06-21 02:36 UTC, merged